#!/usr/bin/env bash

set -ex

: ${UPDATE_SCHEMA:=1}

function usage() {
cat <<EOT
$0 [ARGS]
  -n suppress download of latest schema
  -v [NUM] version number to generate (3|4)
EOT
exit $1
}

while getopts "hnv:" opt; do
  case $opt in
    n)
      UPDATE_SCHEMA=0
      ;;
    v)
      VERSION=$OPTARG
      VERSION_LABEL="v${VERSION}"
      ;;
    h)
      usage 1
      ;;
    \?)
      usage 0
      ;;
    esac
done

if [ -z "${VERSION}" ]; then
  usage 1
fi

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

if [ $UPDATE_SCHEMA -eq 1 ]; then
curl -so ${VERSION_LABEL}/schema.json https://api.heroku.com/schema \
  -H "Accept: application/vnd.heroku+json; version=3"
fi

go get -u github.com/interagent/schematic/cmd/schematic
schematic ${VERSION_LABEL}/schema.json > ${VERSION_LABEL}/heroku.go

sed -E -i '' \
  's/^([[:space:]]*Version[[:space:]]*=[[:space:]]*)""$/\1"v3"/' \
  ${VERSION_LABEL}/heroku.go

gofmt -w ${VERSION_LABEL}/heroku.go
